### ISSUE TITLE
Diagnostic Report in blank

### ISSUE THREAD

**Issue by rareza35** [tegin/medical-fhir#126]
Hello, I am trying to test this addon for a clinic, the Clinic -> Diagnostic Report section has no option to create and/or modify, is it an error or is a procedure missing?

Thanks for your help!

![diagnostic report](https://user-images.githubusercontent.com/63313661/139516734-912a0c59-769b-467e-9d43-87adfa34e68c.png)
p

**Comment by etobella** [comment]
Reports are created from an encounter using a template. Create an encounter on administration encounters, then you can create a diagnostic report from there :wink:

**Comment by etobella** [comment]
Did it work?
