### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by mrcroc** [tegin/medical-fhir#137]
I'd like to give this a try, but I'm currently struggling as to how to get started: `README.rst` says "go to 'Medical / Configuration / Settings'", but how does one get to the point where "Medical" shows inside Odoo? I've tried both with versions 15.0 and 13.0 so far. Is this a matter of first installing module `medical_administration` e.g. with `git clone` into `addons_path`?

**Comment by etobella** [comment]
You need to install the module, just, add medical-fhir to you addons_path. Right now, it works with 13. No migration to 15 yet

**Comment by mrcroc** [comment]
@etobella Thx for your quick reply. And addition into `addons_path` must be done via `git clone`, for the is no `zip`-file version yet (as for modules in the Odoo app store), right?

**Comment by etobella** [comment]
I think so
