### ISSUE TITLE
What licenses apply?

### ISSUE THREAD

**Issue by mrcroc** [tegin/medical-fhir#138]
OCA/vertical-medical#229 suggests that an earlier attempt (e.g. including Odoo module `medical_procedure`) was abandoned because of licensing issues. This repo does not yet include `LICENSE.md`. So what is/are applicable license/s and is there a roadmap for this project?

**Comment by etobella** [comment]
Each module has a license on the manifest. Anyway,bthis was created all by us, so we can change the license if necessary

**Comment by etobella** [comment]
It has no relation with vertical medical as the creation process was completely independent

**Comment by mrcroc** [comment]
Alright, I see. Thanks for the clarification.
