### ISSUE TITLE
Start to learn the repo

### ISSUE THREAD

**Issue by hitrosol** [tegin/medical-fhir#154]
Hi @etobella, nice repo.

I'm trying to understand the workflow of the modules. I guess there are lot of features need to add to have the complete clinic / hospital system. 

I still don't get how to run this. 
Usually, at least per my experience went to clinic; the patient will be registered in the front desk and asked about purpose of their visit, what kind of ill, and to which doctor they want to see, according to the available schedule, the front desk also can recommend the doctor according to the sympthome, etc. 

After that qeueu system will show the current qeueing and the patient will wait until their time. 

In the room, the doctor will examine the patient, talk to the patient, etc and write the result of the examination and if it necesarry give prescription, or lab test order, etc. 

If there is a lab order, the patient will go the lab, get the blood, urine, etc test, and the result will be inputted to the system by the lab operator. Of course the lab operator already know the order since it's orderd by the doctor. 

In pharmacy, the medicines are prepared after the patient closed the order by pay in cash or get confirmation from the insurance company. 

Of course those are a simply workflow and can be expand based on the complexity of the medicak center.  There are type of encounters  such as inpatient, outpatient, etc. 

I know you get reference from FHIR, but do you have any other roadmap ot this development? I get feeling that this repo is just beginning, for many other modules on going. 

Since there are other modules will be added, do you have plan to breakdown the menu so it will not be too long for one main menu?
Do you have plan to move this to OCA officially?

Thanks

**Comment by etobella** [comment]
Yes, there is much more work after it the repository of a real implementation can be found with github.com/tegin/cb-medical. Anyway, If you want, you can contact me in a private channel and I can show you a real environment. We do not have all the FHIR options enabled, but we are evolving the system one step at a time.

We will try to port it to OCA with the 14.0 version (we are still migrating it :smile: )

**Comment by hitrosol** [comment]
sure, I will contact you in Discord
