### ISSUE TITLE
Another fhir implementation

### ISSUE THREAD

**Issue by amon-ra** [tegin/medical-fhir#51]
I have found this another fhir implementation:
[https://github.com/ForgeFlow/odoo-fhir](url)
It seams outdated but it has more modules than this repository. ¿What are the diferences in base implementation?¿What are the modules that this repository lacks?

I would like to collaborate to port missing features. Thanks in advice

**Comment by etobella** [comment]
That module was a first try on the creation of a set of medical modules, however this repo is more complex an maintained.
What are you interested to migrate or develop? If you think this is interesting we could propose the set of modules to OCA. Also, maybe we have something on a private repo that could fill your expectations

**Comment by etobella** [comment]
@amon-ra Have you checked our comments? Do you have any other comments?

**Comment by amon-ra** [comment]
We are searching a base set of modules to develop from. It is not a medical aplication, is a soccer team manager and we need to add insurance and injury history form players (company employees). We want that our work could be reused.

Thanks for your time.

**Comment by etobella** [comment]
:thinking: Well this set of modules is expected for a medical company (hospital, clinic) not to check data of employees, maybe you might need to create a module linking employees and patients. 

Right now, we are not expecting to create a module for medical reports 
https://www.hl7.org/fhir/diagnosticreport.html

But we are talking to merge here a module for documents (http://hl7.org/fhir/documentreference.html) that might give you a solution for records. Also, conditions might work for you with low inversion.
