### ISSUE TITLE
How to collaborate / finance ?

### ISSUE THREAD

**Issue by TheCloneMaster** [tegin/medical-fhir#79]
Hi,

We are in need of medical modules for Odoo.

We can contribute with development time and/or financially to the project, as we would like to update to Odoo v14.
How should we proceed?

How is this one related to original vertical-medical, oeMedical before that.... ?

Thanks,
-Mario

**Comment by etobella** [comment]
It does not depend on them as there was a licensing problem. It was all made new. If you want to collaborate we can move it to OCA vertical medical.

We are working on the migration to 13, as openupgrade has not been finished for 14.

Which kind of need do you have?

**Comment by etobella** [comment]
@TheCloneMaster do you have some information of the kind of needs do you have? Do you need a call or something?

**Comment by TheCloneMaster** [comment]
Hi Enric, thanks for your fast reply.

I worked with Medical since it was still being driven by Luis Falcon under
OpenERP.  When he moved away to Tryton, I stayed and keep working on Odoo,
updating the code to v8/v10.  At some point those folks from India made a
massive take over, even removing copyrights and a lot of code logic, and
then Lasley started contributing and I had to move to some other projects
and lost track of this one....

Now we have a couple new prospects, and I was assigned to understand the
current state.  I see vertical medical is at v12, while this one is being
migrated to v13.

Is functional coverage the same/similar or this is completely different?
If different, is it possible to integrate both, maybe moving this to
vertical medical as you suggested before?  Or do you prefer to focus on
this one?  Do you have any planned/pending tasks where we could help?

I will configure a couple environments to test both, but your help and
knowledge will be appreciated!!  We could even work together with these
prospects, that way we contribute back to your work.

Regards,
-Mario

**Comment by etobella** [comment]
well, vertical-medical was frozen on 11, if I remember correctly... 
Functionality might be similar to the original vertical medical, but was created from scratch and following the schema provided by http://www.hl7.org/fhir/
This repo is just the basic structure, but we have joined this with sales, point_of_sale, commissions, document generation and even integration with basic HL7. 
If you want to work in this implementation, we can move it to vertical-medical, I think that would be the proper place.

If you are interested, we can show you a demo environment.

**Comment by TheCloneMaster** [comment]
Great!

I think moving to vertical-medical is good to possible attract more
contributions.
Maybe keep the fhir prefix or suffix to these modules, so they are not
mixed with the original ones, or try to integrate both under fhir style...

As for the demo, I will appreciate that, and then we can talk about
collaboration and partnership...

Regards,
-Mario

**Comment by etobella** [comment]
Changing the name might be problematic, as we already have them on production. If we want to do this, must be done on a major version change.

After checking internally, we are afraid to put them on vertical-medical due to some issues that were found with licenses on vertical-medical. We can move it later, but I would prefer to talk with OCA Board in order to make this properly.

Also, original vertical-medical is no longer maintained, and this work has nothing to do with that (I made the code from zero in order to avoid this kind of issues), so, IMO, we don't need to keep any kind of relation or migration scripts.

https://github.com/OCA/vertical-medical/issues/183

**Comment by TheCloneMaster** [comment]
Code location/naming is not my first priority, so we are ok working in your
current repository

**Comment by etobella** [comment]
gr8! If you want, we can make a call (I need some time in order to prepare all) so I can show you our work.

**Comment by TheCloneMaster** [comment]
Thanks !!
Just let me know when it is fine for you to make the call.

Regards,
-Mario

**Comment by etobella** [comment]
Can you contact me privately in order to propose you dates??

**Comment by marcos-mendez** [comment]
Hello guys, I work at Kimenz.com.br we run 96 hospitals and 863 basic health units in Brazil 

I suggest we make an OCA chat group or something to disscus this

i really want to contribute to this changes and updates as they are mandatory for us. Also we have to notice that a vertical medical is a wrong term because clinical engeneering should be integrated with the field service and also the supply assets management

I sugest something like healthcare-vertical

**Comment by etobella** [comment]
What do you expect by field service and engineering?

**Comment by marcos-mendez** [comment]
So in Hospital Management we have 3 Sectors

Clinical Engeneering responsible for fixing and maintaining hospital
equipment
We have Medical that is what the software already does, patient records etc
And Supply Chain of consumables for medicine and also equipment parts
(today it works 50%) because it only tracks medicine and drugs not part and
equipment consumables

Em qui., 17 de jun. de 2021 às 11:11, Enric Tobella <
***@***.***> escreveu:

**Comment by etobella** [comment]
In our case:

- Fixing and maintaining equipment is managed by `maintenance` modules 
- Medical: Manages patient records
- Supply of consumables, managed also by medical using medication.request, I know it is intended for medication, but it can be extended to all kind of products

**Comment by marcos-mendez** [comment]
A Better integration of those modules could provide better meta analytics
of pandemic situation scarce resources in some regions or even can help to
promote public health politics for a better comprehension of the medical
and healthcare system worldwide. A think a better made debate and exchange
of ideas is necessary before attempting to rebuild or recreate anything.

Em qui., 17 de jun. de 2021 às 12:03, Enric Tobella <
***@***.***> escreveu:

**Comment by marcos-mendez** [comment]
maintenance
field-service
reapir should also work together in this case scenario

**Comment by etobella** [comment]
field-service (at least as defined by OCA) is not defined properly for medical behavior, at least is not following in any case the FHIR methodology. I raised some comments some time ago, but they were rejected. They say it can be used for medical, but it is not IMO and in my experience. In any case, medical process generate a lot of elements when something is processed, for example, a CT must generate (at least):

* A Consent Document
* An order for the machine (Worklist)
* An order for the technician
* An order for the physician
* A record delivery

This is a simple case, but has generated a lot of different elements and tasks with different behavior. This was not a goal on field-service, but here it is implemented.

Repair is intended for repairing products, not equipment. Medical equipment on a hospital should be repaired using maintenance.

If you are talking of a company that makes and maintains some medical devices, then it should use repair and field-service, but not medical modules, as they do not need patient records.

**Comment by marcos-mendez** [comment]
Ok yes but the non conformity modules integrate with those and by W.H.O
recommend to follow non conformity standards as well as complementary
reports for services in the health sectors. As this would be a vertical a
most global scenario should be considered right?

Em qui., 17 de jun. de 2021 às 12:42, Enric Tobella <
***@***.***> escreveu:

**Comment by etobella** [comment]
Might be interesting, in any case, I would like to see how to fit it inside FHIR.

**Comment by TheCloneMaster** [comment]
We could have specific additional modules for these other areas, not
necessarily included in FHIR methodology....

**Comment by etobella** [comment]
Sure! That's what we did, but it was specific to our way to work

**Comment by marcos-mendez** [comment]
Do you want to schedule a meeting?

Em sex., 18 de jun. de 2021 às 16:23, Enric Tobella <
***@***.***> escreveu:

**Comment by etobella** [comment]
Sure! I contacted you by discord
